// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtoparkSistemi.Data;

#nullable disable

namespace OtoparkSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513203416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OtoparkSistemi.Models.Abonelik", b =>
                {
                    b.Property<int>("AbonelikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonelikId"));

                    b.Property<string>("AbonelikTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AbonelikId");

                    b.HasIndex("AracId");

                    b.ToTable("Abonelikler");
                });

            modelBuilder.Entity("OtoparkSistemi.Models.Arac", b =>
                {
                    b.Property<int>("AracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AracId"));

                    b.Property<string>("AracTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SahibiAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SahibiTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AracId");

                    b.HasIndex("Plaka")
                        .IsUnique();

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("OtoparkSistemi.Models.GirisKayit", b =>
                {
                    b.Property<int>("KayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KayitId"));

                    b.Property<bool>("AbonelikKullanildiMi")
                        .HasColumnType("bit");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OdemeDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("OdenenUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ToplamSure")
                        .HasColumnType("int");

                    b.HasKey("KayitId");

                    b.HasIndex("AracId");

                    b.ToTable("GirisKayitlari");
                });

            modelBuilder.Entity("OtoparkSistemi.Models.Tarife", b =>
                {
                    b.Property<int>("TarifeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarifeId"));

                    b.Property<string>("AracTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GecerlilikBaslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GecerlilikBitis")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GunlukMaksimum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaatlikUcret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TarifeId");

                    b.ToTable("Tarifeler");
                });

            modelBuilder.Entity("OtoparkSistemi.Models.Abonelik", b =>
                {
                    b.HasOne("OtoparkSistemi.Models.Arac", "Arac")
                        .WithMany("Abonelikler")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("OtoparkSistemi.Models.GirisKayit", b =>
                {
                    b.HasOne("OtoparkSistemi.Models.Arac", "Arac")
                        .WithMany("GirisKayitlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("OtoparkSistemi.Models.Arac", b =>
                {
                    b.Navigation("Abonelikler");

                    b.Navigation("GirisKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
